version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/aks/devcontainer.json"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/aks_auto"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/backstage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/flux"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/k3d"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/kind"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/radius-dev"
    schedule:
      interval: "weekly"