name: Build Radius Dev Container

"on":
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      # Use a specific commit to avoid build issues caused by gnostic-models v0.7.0 breaking changes
      # This commit is from before the dependency update on July 3, 2025 that introduced the issue
      - name: Checkout radius-project/radius
        uses: actions/checkout@v4
        with:
          repository: radius-project/radius
          ref: ba46c2d872bcb8b8dfb9ea3b31bfd4c92f1021f2  # Use commit before gnostic-models v0.7.0 breaking change
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/radius-dev
          cacheFrom: ghcr.io/${{ github.repository_owner }}/radius-dev
          push: always
          imageTag: |
            latest
            commit-ba46c2d8