name: Build Radius Dev Container

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout radius-project/radius
        uses: actions/checkout@v4
        with:
          repository: radius-project/radius
          ref: main
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/radius-dev
          cacheFrom: ghcr.io/${{ github.repository_owner }}/radius-dev
          push: always
          imageTag: |
            latest
            ${{ github.run_number }}
            weekly-${{ github.run_number }}